[docs] Add Frontend Setup Documentation
web3wagers/gostarkme pull request #105
Opened 2024-09-29 00:52 UTC by jsandinoDev

# Pull Request

- [✅] Closes #84 
- [✅] Added tests (if necessary)
- [✅] Run tests
- [✅] Run formatting
- [✅] Commented the code

## Changes description

1.  Add the frontend setup documentation for the local and production deployments.
2. Add `&apos;`  in the `frontend/gostarkme-web/app/fund/[fundId]/page.tsx` to avoid this error in the production deployment:

<img width="718" alt="Screenshot 2024-09-28 at 12 17 09 AM" src="https://github.com/user-attachments/assets/38c4b824-3f69-4f59-adcf-6a6321c3cbdd">

## Time spent breakdown

3 hours.

2024-09-29 20:21 UTC, adrianvrj requested changes

2024-09-29 20:21 UTC, adrianvrj commented on frontend/README.md
> +- Install Node/Npm (see [here](https://nodejs.org/en))
could you add the working version (20.15.1), and recommend the use of a node version manager

2024-09-30 15:12 UTC, adrianvrj approved these changes
LGTM

2024-09-30 17:09 UTC, jsandinoDev commented
Conflicts solved! @adrianvrj

2024-09-30 17:10 UTC, merged