[Feat] Add dashboard page
web3wagers/gostarkme pull request #106
Opened 2024-09-29 04:17 UTC by sanieni6

# Pull Request

- [✅] Closes #89 

## Changes description

1. Create the dashboard page
2. Create a hook to get the height and width of any component
3. refactor the animation to make it works with the fund card and fix the x-scroling in the root page

Note: the dashboard page is fully responsive

## Current output
1. Dashboard page
![image](https://github.com/user-attachments/assets/37ee23f9-9378-4f05-b2d5-24acfd69e0ba)

## Time spent breakdown

1 hour

## Comments

Any other details you might want to share.

2024-09-29 20:30 UTC, adrianvrj requested changes

2024-09-29 20:30 UTC, adrianvrj commented on frontend/gostarkme-web/components/dashboard/fundCard.tsx
> +            {fund.type} {fund.type === "Project" ? "🚀" : "🎗️"}
Could you please use the HTML representation of the emojis:
rocket: U+1F680
heart: U+1FAC0


<br class="Apple-interchange-newline">[U+1FAC0](https://unicode.org/emoji/charts/full-emoji-list.html#1fac0)

2024-09-30 13:10 UTC, sanieni6 commented on frontend/gostarkme-web/components/dashboard/fundCard.tsx
> +            {fund.type} {fund.type === "Project" ? "🚀" : "🎗️"}
Solved!

2024-09-30 13:44 UTC, adrianvrj requested changes

2024-09-30 13:44 UTC, adrianvrj commented on frontend/gostarkme-web/app/dashboard/page.tsx
> +        <span className="ml-2 text-yellow-400">✨</span>
Please use the HTML code for this emoji here too 🙏🏻

2024-09-30 13:58 UTC, sanieni6 commented on frontend/gostarkme-web/app/dashboard/page.tsx
> +        <span className="ml-2 text-yellow-400">✨</span>
Done!

2024-09-30 14:01 UTC, adrianvrj approved these changes

2024-09-30 14:08 UTC, adrianvrj commented
LGTM! tysm sir

2024-09-30 14:08 UTC, merged

2024-09-30 14:42 UTC, sanieni6 commented
My first ever OSS man, thank you so much guys, i am gonna portrait this PR

2024-09-30 15:32 UTC, adrianvrj commented
> My first ever OSS man, thank you so much guys, i am gonna portrait this PR

first of many, congrats homie! 🥳