feat: test_fund_manager
web3wagers/gostarkme pull request #118
Opened 2024-10-02 00:52 UTC by diegoTech14

# Pull Request

- [ ] Closes #90 
- [ ] Added tests (if necessary)
- [ ] Run tests
- [ ] Run formatting
- [ ] Commented the code

## Changes description

Describe what your changes will do and any TODOs there might be in the future related to the issue you are closing.

## Current output

Give evidence like screenshots of what your job looks like.

## Time spent breakdown

Give a breakdown on the time you used to solve the issue you are closing.

## Comments

Any other details you might want to share.

2024-10-02 04:48 UTC, EmmanuelAR requested changes

2024-10-02 04:48 UTC, EmmanuelAR commented on contracts/tests/test_fund_manager.cairo
> +    let fund_manager_contract = IFundManagerDispatcher { contract_address };
Pending to assert constructor values, like owner and class hash that you set in the constructor, feel free to add get methods to that values to assert.

2024-10-02 19:50 UTC, diegoTech14 commented on contracts/tests/test_fund_manager.cairo
> +    let fund_manager_contract = IFundManagerDispatcher { contract_address };
Got it sir, I'm on it!

2024-10-02 21:11 UTC, diegoTech14 commented on contracts/tests/test_fund_manager.cairo
> +    let fund_manager_contract = IFundManagerDispatcher { contract_address };
I updated the issue with the suggestion and some details were fixed.

2024-10-03 02:13 UTC, EmmanuelAR approved these changes

2024-10-03 02:14 UTC, EmmanuelAR commented
LGTM! Excellent work @diegoTech14

2024-10-03 02:14 UTC, merged