[feat] Add connect wallet functionality
web3wagers/gostarkme pull request #123
Opened 2024-10-03 07:50 UTC by jimenezz22

# Pull Request

- [x] Closes #110 
- [x] Added tests (if necessary)
- [x] Run tests
- [x] Run formatting
- [ ] Commented the code

## Changes description

Describe what your changes will do and any TODOs there might be in the future related to the issue you are closing.
- Use useState to manage wallet connection status (walletConnection), storing the wallet address and wallet object.
- The handleConnect function triggers wallet connection via connect() and retrieves the wallet's address.
- Upon successful connection, stores the address in the component state and persists it in localStorage for session persistence.
- The handleDisconnect function disconnects the wallet via disconnect(), clears the connection state, and removes relevant data from localStorage.
- The "Connect wallet" button dynamically changes to display the connected wallet’s shortened address (e.g., 0x1234...abcd) when a wallet is connected.
- A disconnect button allows the user to disconnect their wallet with a simple UI interaction.

## Current output

![giphy](https://github.com/user-attachments/assets/56383c4a-9620-43be-bc3d-d495f56d3d37)

Before connecting:

<img width="1512" alt="Screenshot 2024-10-03 at 1 40 37 AM" src="https://github.com/user-attachments/assets/94ea4b4f-b3be-49d7-a3d1-e17adbf176ca">

During connecting:

<img width="543" alt="Screenshot 2024-10-03 at 1 40 17 AM" src="https://github.com/user-attachments/assets/21748ce9-e1af-4a35-80b0-daabd617822e">
<img width="1512" alt="Screenshot 2024-10-03 at 1 41 31 AM" src="https://github.com/user-attachments/assets/98819c8d-6fe9-406e-85ce-4503b61cc09c">
<img width="1512" alt="Screenshot 2024-10-03 at 1 41 15 AM" src="https://github.com/user-attachments/assets/c83e6f56-651a-4915-a9e5-2897d89e1734">

After connecting:
<img width="1512" alt="Screenshot 2024-10-03 at 1 40 51 AM" src="https://github.com/user-attachments/assets/80c97fc8-a4b1-4c90-a487-f910d668d621">

## Time spent breakdown

Give a breakdown on the time you used to solve the issue you are closing.

- Approximately 4/5 hours divided into two days. I read the Starknetkit documentation required to connect the wallets, saw their examples and adapted it to what is required for this issue

## Comments

Any other details you might want to share.
- None

2024-10-03 15:09 UTC, adrianvrj commented on frontend/gostarkme-web/next.config.mjs
please do not upload the changes for this file, we have to add it to the .gitignore actually lol

2024-10-03 15:10 UTC, adrianvrj commented on frontend/gostarkme-web/package.json
please do not upload the changes for this file

2024-10-03 15:10 UTC, adrianvrj commented on frontend/gostarkme-web/yarn.lock
please do not upload the changes for this file

2024-10-03 15:10 UTC, adrianvrj commented on frontend/gostarkme-web/.env
please do not upload the changes for this file

2024-10-03 15:11 UTC, adrianvrj requested changes
Looks good, just a couple of changes

2024-10-03 20:36 UTC, jimenezz22 commented on frontend/gostarkme-web/package.json
@adrianvrj is important to use "starknet": "^6.7.0", and "starknetkit": "^1.1.5" as a versions to ensure the wallet connector funcionality

2024-10-03 20:38 UTC, adrianvrj commented on frontend/gostarkme-web/package.json
I see, leave this change then, ty

2024-10-04 00:38 UTC, adrianvrj approved these changes

2024-10-04 00:43 UTC, adrianvrj commented
@jimenezz22 seems like something went wrong when building the frontend

2024-10-04 00:46 UTC, jimenezz22 commented
> @jimenezz22 seems like something went wrong when building the frontend

checking

2024-10-04 01:07 UTC, jimenezz22 commented
@adrianvrj Everything looks good right now

<img width="1186" alt="Screenshot 2024-10-03 at 7 00 04 PM" src="https://github.com/user-attachments/assets/49aae3ac-4094-475e-8e4e-c5f3fcbc7f83">

2024-10-04 01:10 UTC, adrianvrj commented
@jimenezz22 everything looks good now, tysm, great work homie!

2024-10-04 01:10 UTC, merged