[#7] Adding donator contract
web3wagers/gostarkme pull request #15
Opened 2024-08-06 22:36 UTC by EmmanuelAR

<img width="1710" alt="Captura de pantalla 2024-08-06 a la(s) 4 35 39 p  m" src="https://github.com/user-attachments/assets/830c8b62-18a8-4c98-b3a7-1409e13e20c0">
#7

2024-08-06 23:58 UTC, adrianvrj approved these changes

2024-08-07 01:09 UTC, adrianvrj requested changes
Consider adding a level up logic where the user can only level up after reaching certain amount of donations, that way we prevent user from calling the level up function without any restrictions

2024-08-13 01:31 UTC, EmmanuelAR commented
okk thanks, on it @adrianvrj

2024-08-14 22:36 UTC, EmmanuelAR commented
This pr with be close and open a new one cuz some changes surge in today meetings

2024-08-14 22:36 UTC, closed without merging