[feat] Emit event when fund contract is deployed #136
web3wagers/gostarkme pull request #158
Opened 2024-10-25 09:12 UTC by Gianfranco99

# Pull Request

- [ ] Closes #136 
- [ ] Added tests (if necessary)
- [x] Run tests
- [x] Run formatting
- [] Commented the code

## Changes description

What I did was add the fundDeployed event with the owner as the key. This event is emitted once the contract has been deployed successfully.

## Current output

Give evidence like screenshots of what your job looks like.

## Time spent breakdown

Give a breakdown on the time you used to solve the issue you are closing.

## Comments

Any other details you might want to share.

2024-10-25 16:26 UTC, EmmanuelAR requested changes

2024-10-25 16:26 UTC, EmmanuelAR commented on contracts/src/fundManager.cairo
> +            self.funds.write(self.current_id.read(), address_0);
Please merge your branch with the latest changes because that variable address_0, is not the latest

2024-10-25 16:26 UTC, EmmanuelAR commented on contracts/src/fundManager.cairo
> +            self.funds.write(self.current_id.read(), address_0);
Also change the reference of the address_0 in the event

2024-10-25 16:27 UTC, EmmanuelAR commented
Thks so much for your work @Gianfranco99 just some changes!

2024-10-26 11:43 UTC, Gianfranco99 commented on contracts/src/fundManager.cairo
> +            self.funds.write(self.current_id.read(), address_0);
Done @EmmanuelAR !

2024-10-26 15:55 UTC, EmmanuelAR approved these changes

2024-10-26 15:56 UTC, merged