feat: add emit event to receiveDonation function
web3wagers/gostarkme pull request #161
Opened 2024-10-25 17:53 UTC by NueloSE

# Pull Request

Fixes #139 

- [ ] Closes #
- [ ] Added tests (if necessary)
- [x] Run tests
- [x] Run formatting
- [x] Commented the code

## Changes description

Add emit event to receiveDonation function

## Current output

Give evidence like screenshots of what your job looks like.

## Time spent breakdown

< 5hrs

## Comments

formatted using `scarb fmt`

2024-10-25 20:28 UTC, EmmanuelAR requested changes
Exc work @NueloSE just some changes!

2024-10-25 20:28 UTC, EmmanuelAR commented on contracts/src/fund.cairo
> +        pub donor_address: ContractAddress,
typo: donator

2024-10-25 20:28 UTC, EmmanuelAR commented on contracts/src/fund.cairo
> +            //TODO: Calculate balance to deposit in owner address and in fund manager address (95%
Leave original, do not separate it

2024-10-25 23:35 UTC, EmmanuelAR approved these changes
LGTM

2024-10-25 23:39 UTC, EmmanuelAR requested changes

2024-10-25 23:39 UTC, EmmanuelAR commented on contracts/src/fund.cairo
> +                        donor_address: get_caller_address(),
Also change the event, please run the scarb build and fmt

2024-10-26 04:09 UTC, NueloSE commented
@EmmanuelAR  fixed the typo now

2024-10-26 06:37 UTC, EmmanuelAR requested changes

2024-10-26 06:37 UTC, EmmanuelAR commented on contracts/src/fund.cairo
> +        pub current_balance: u256,
the key will be the donator address not the current balance

2024-10-26 16:00 UTC, merged