Refactor current_goal_state
web3wagers/gostarkme pull request #167
Opened 2024-10-28 15:56 UTC by saimeunt

# Pull Request

- [x] Closes #142 
- [ ] Added tests (if necessary)
- [x] Run tests
- [x] Run formatting
- [x] Commented the code

## Changes description

This PRs refactors the current_goal_state variable in favor of an ERC20 token balance.
The ERC20 token address has been added as a parameter of the fund to be able to create funds compatible with any ERC20 token.
The ongoing tests for withdraw might be impacted by this refactor.

## Time spent breakdown

Half a day spent on reading the codebase, refactoring according to guidance and modifying tests accordingly.

2024-10-29 02:29 UTC, EmmanuelAR requested changes
tks @saimeunt for the help, some changes

2024-10-29 02:29 UTC, EmmanuelAR commented on contracts/src/fund.cairo
> +        fn token(self: @ContractState) -> IERC20Dispatcher {
Change this function name to token_dispatcher pls

2024-10-29 02:29 UTC, EmmanuelAR commented on contracts/src/fund.cairo
> +        self.token_address.write(token_address);
We are working now only on a poc using only starknet, so please remove to receive the token address like a parameter in the constructor and change it to use the starknet address, it is in the constants pls

2024-10-29 02:29 UTC, EmmanuelAR commented on contracts/src/fund.cairo
>          fn getCurrentGoalState(self: @ContractState) -> u256 {
please change the name of the method to get_current_goal_state please, and refresh the reference

2024-10-29 02:29 UTC, EmmanuelAR commented on contracts/src/fundManager.cairo
> +    fn newFund(ref self: TContractState, name: felt252, goal: u256, token_address: ContractAddress);
remove the parameter, check the previous comment, the address will be starknet for this momment

2024-10-29 02:33 UTC, bitfalt requested changes

2024-10-29 02:33 UTC, bitfalt commented on contracts/src/token.cairo
Could you explain why this file was created? We see it is being used for the tests to simulate an ERC20 token, since there is not STRK, USDC or any token contract address in a test environment. 

A workaround for this could be to fork Sepolia or Mainnet in Foundry since the contracts exist there. You can check the following PR #159 specifically the `contracts/Scarb.toml` file to see how it is done.

2024-10-29 11:46 UTC, saimeunt commented
@bitfalt @EmmanuelAR I just made the requested changes, thanks for reviewing 👌

2024-10-30 02:30 UTC, EmmanuelAR approved these changes
LGTM

2024-10-30 02:37 UTC, bitfalt approved these changes
lgtm! i loved how you did the test. Great job! :D

2024-10-30 02:38 UTC, merged