[test] Test event emit when user withdraw fund's balance
web3wagers/gostarkme pull request #170
Opened 2024-10-31 02:06 UTC by DiegoB1911

# Pull Request

- [x] Closes  #143 
- [x] Added tests (if necessary)
- [x] Run tests
- [x] Run formatting
- [ ] Commented the code

## Changes description

This PR introduces a test to verify that the correct event is emitted when the withdraw function is called

## Current output

![image](https://github.com/user-attachments/assets/e25b7792-37f1-4c8a-805a-59e60268348c)

## Time spent breakdown

Give a breakdown on the time you used to solve the issue you are closing.

## Comments

Any other details you might want to share.

2024-10-31 02:35 UTC, DiegoB1911 commented
Sure, I'm working on it

2024-10-31 18:10 UTC, EmmanuelAR requested changes

2024-10-31 18:10 UTC, EmmanuelAR commented on contracts/src/fund.cairo
> +            assert(self.get_current_goal_state() >= 0, 'Fund hasnt reached its goal yet');
Leave the original validation please

2024-10-31 18:10 UTC, EmmanuelAR commented on contracts/tests/test_fund.cairo
> +
I know that you create the setup_donation method to avoid to repeat code but in this case please leave it ass the original

2024-10-31 18:10 UTC, EmmanuelAR commented
Exc work Diego @DiegoB1911 some changes tkssss

2024-10-31 18:14 UTC, EmmanuelAR requested changes

2024-10-31 18:14 UTC, EmmanuelAR commented on contracts/src/fund.cairo
> +            assert(self.get_current_goal_state() >= 0, 'Fund hasnt reached its goal yet');
the reason because when the user withdraw the fund the expected behaivor is that all the money is fund so the current budget will be 0

2024-11-01 02:26 UTC, EmmanuelAR approved these changes
LGTM

2024-11-01 02:27 UTC, merged