[feat] Add asserts to set_name
web3wagers/gostarkme pull request #260
Opened 2024-11-22 17:00 UTC by jsanchez556

# Pull Request

- [ ] Closes #
- [ X] Added tests (if necessary)
- [ X] Run tests
- [ ] Run formatting
- [ ] Commented the code

## Changes description

1. Locate the set_name function in contracts/src/fund.cairo and enhance it by adding validation to ensure the caller is either VALID_ADDRESS_1 or VALID_ADDRESS_2.
2. Add a test to verify that the set_name function works correctly when called by VALID_ADDRESS_1 or VALID_ADDRESS_2.
3. Add a test to confirm that the set_name function does not work when called by an address other than VALID_ADDRESS_1 or VALID_ADDRESS_2.

## Current output

![Screenshot from 2024-11-22 10-54-04](https://github.com/user-attachments/assets/d4cdd544-3cf9-4baf-86d9-c5d105649d6a)

## Time spent breakdown

2 hours.

## Comments

Thank you for the opportunity to contribute to this great project

2024-11-22 17:50 UTC, EmmanuelAR requested changes

2024-11-22 17:50 UTC, EmmanuelAR commented on contracts/src/fund.cairo
> -            assert!(self.owner.read() == caller, "You are not the owner");
keep this assert, the owner can call it too

2024-11-22 17:50 UTC, EmmanuelAR commented on contracts/tests/test_fund.cairo
> +#[should_panic(expected: ("You are not the admin",))]
Add test when the owner call, keep the assert, i left u a comment
Keep test_set_name_not_admin test is ok

2024-11-23 20:13 UTC, EmmanuelAR approved these changes
LGTM, great work g!

2024-11-23 20:37 UTC, merged

2024-12-05 22:03 UTC, jsanchez556 commented
@all-contributors please add @jsanchez556 for code