Test: Set Contact Handle #259
web3wagers/gostarkme pull request #270
Opened 2024-11-25 21:50 UTC by ChrisFernandezVivas

# Pull Request

- [ x] Closes 259
- [ x] Added tests (if necessary)
- [x ] Run tests
- [ ] Run formatting
- [x ] Commented the code

## Changes description

add a test for a set_contact_handle method, the test check with all authorized users and try with 1 another user, the test always fails because when another user try call the function the test fail

## Current output

<img width="803" alt="Captura de pantalla 2024-11-25 a las 3 45 57 p  m" src="https://github.com/user-attachments/assets/7c977027-59ab-41ee-b104-3154798d9b94">

## Time spent breakdown

5 hours

## Comments

i putted a #[should_panic] so if you remove this the test always fail

2024-11-25 21:53 UTC, adrianvrj commented on contracts/tests/test_fund.cairo
> +
please remove this blank spaces

2024-11-25 21:54 UTC, adrianvrj commented on contracts/tests/test_fund.cairo
> +    dispatcher.set_contact_handle(CONTACT_HANDLE_2());//set
remove this ```set/get``` comments please

2024-11-25 21:54 UTC, adrianvrj requested changes
just a couple changes from my side, did you run scarb fmt?

2024-11-25 22:01 UTC, EmmanuelAR requested changes

2024-11-25 22:01 UTC, EmmanuelAR commented on contracts/tests/test_fund.cairo
> +fn test_set_contact_handle(){
Please divided the test in success case and error case

2024-11-25 22:10 UTC, ChrisFernandezVivas commented on contracts/tests/test_fund.cairo
> +    dispatcher.set_contact_handle(CONTACT_HANDLE_2());//set
okey perfect I will do

2024-11-25 22:10 UTC, ChrisFernandezVivas commented on contracts/tests/test_fund.cairo
> +
good

2024-11-25 22:11 UTC, ChrisFernandezVivas commented on contracts/tests/test_fund.cairo
> +fn test_set_contact_handle(){
okey thank you for your feedback

2024-11-26 01:19 UTC, EmmanuelAR approved these changes
lgtm

2024-11-26 01:28 UTC, adrianvrj approved these changes

2024-11-26 01:28 UTC, merged