Changes:
web3wagers/gostarkme pull request #38
Opened 2024-08-15 04:01 UTC by EmmanuelAR

1- Add donator contract
2-Add donatorManager contract
3-Add error constant
4-Add donator constant
5-Add new constants references in all the contracts 6-Add new comments to separete the code in sections

2024-08-15 04:04 UTC, EmmanuelAR commented
TICKETS:
#33
#22
#7

2024-08-17 22:52 UTC, adrianvrj commented on contracts/src/constants/donator/donator_constants.cairo
> +    pub const INICIAL_LEVEL: u32 = 1;
This should be INITIAL

2024-08-17 22:52 UTC, adrianvrj commented on contracts/src/constants/donator/donator_constants.cairo
> +    pub const INICIAL_MAX_STARKS_DONATION_TO_NEXT_LEVEL: u64 = 10;
Same here

2024-08-17 22:53 UTC, adrianvrj requested changes
Couple of orthography changes, everything else looks good

2024-08-17 23:00 UTC, adrianvrj approved these changes

2024-08-17 23:01 UTC, merged