feat: add allContributors to recognise contributors to the project
web3wagers/gostarkme pull request #96
Opened 2024-09-26 04:13 UTC by raizo07

# Pull Request

- [ ] Closes #
- [ ] Added tests (if necessary)
- [ ] Run tests
- [x] Run formatting
- [x] Commented the code

## Changes description

add allContributors to recognise contributors to the project

## Comments

This will help to recognise and acknowledge all those who have contributed to the project.

2024-10-09 18:50 UTC, adrianvrj commented
@raizo07 could you please resolve the conflicts to merge this?

2024-10-09 19:32 UTC, raizo07 commented
Done @adrianvrj You can merge now

2024-10-10 02:00 UTC, adrianvrj requested changes

2024-10-10 02:00 UTC, adrianvrj commented on README.md
> +
this UML diagram should no longer be here, please remove

2024-10-10 03:45 UTC, raizo07 commented on README.md
> +
resolved @adrianvrj

2024-10-11 02:36 UTC, raizo07 commented
@adrianvrj kindly review it

2024-10-11 03:40 UTC, adrianvrj requested changes

2024-10-11 03:40 UTC, adrianvrj commented on README.md
>  - [@bitfalt](https://t.me/bitfalt)
This should be up there with the other TG handles

2024-10-23 14:10 UTC, adrianvrj approved these changes

2024-10-23 14:10 UTC, merged

2024-11-01 06:05 UTC, raizo07 commented
@all-contributors please add @raizo07 for code

2024-11-06 14:12 UTC, raizo07 commented
@all-contributors please add @raizo07 for code